---
# This workflow integrates ShiftLeft NG SAST with GitHub code scanning
# Visit https://docs.shiftleft.io for help
name: ShiftLeft Code scanning

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: Download ShiftLeft cli
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Build and Analyze
      run: |
          mvn compile package
          jar_name=`ls target/*.jar`
          ${GITHUB_WORKSPACE}/sl analyze --wait --app $(basename $(pwd)) --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --force --java --cpg $jar_name
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Download findings using api and convert to sarif
      run: |
        sudo pip install shiftleft-scan-reports
        slreporter -a $(basename $(pwd)) --branch ${{ github.head_ref || steps.extract_branch.outputs.branch }} -o ${GITHUB_WORKSPACE}/reports
      env:
        WORKSPACE: "src/main/java"
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        SHIFTLEFT_ORG_ID: ${{ secrets.SHIFTLEFT_ORG_ID }}
    - name: Upload sarif
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports
